### ISSUE TITLE
helper relation should be incliuded

### ISSUE THREAD

**Issue by cmungall** [cthoyt/obo-relations-interactions#1]
It looks like you are reusing the helper relation? 

https://oborel.github.io/obo-relations/interaction-relations/

there should be a fresh one per process. So I think the TSV needs two slots for new RO IDs

Any chance you can use RO curies rather than bare numbers :-)

**Comment by cthoyt** [comment]
Right now it's automating generating the four different RO identifiers based on the starting number, but I would be happy to hard code the expected RO CURIEs too

**Comment by cthoyt** [comment]
I've switched the code over to use explicit identifiers rather than to (over-cleverly) calculate them

**Comment by cmungall** [comment]
I think that's safest
