### ISSUE TITLE
typo in orcid prefix

### ISSUE THREAD

**Issue by cmungall** [cthoyt/obo-relations-interactions#2]
https://github.com/cthoyt/obo-relations-interactions/blob/1fc745b03343ffb8e6641cc072d46a1faea60b44/main.py#L21-L23

If only there were some python library that allowed avoiding hardcoding CURIE expansions :-)

**Comment by cthoyt** [comment]
Yes, if only!

**Comment by cthoyt** [comment]
It seems like this reference to `iao` actually wasn't doing anything at all. Not sure why I had it there
